# fly.toml app configuration file generated for projeto-python-web-scrapping-light-novels on 2025-05-14T02:05:09Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'projeto-python-web-scrapping-light-novels'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
